"""Add missing columns to trade_finance_queries

Revision ID: 26ef8906501d
Revises: d0c3f7f26077
Create Date: 2025-02-27 15:42:57.958188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26ef8906501d'
down_revision: Union[str, None] = 'd0c3f7f26077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('trade_finance_queries', sa.Column('task', sa.String(), nullable=True))
    op.add_column('trade_finance_queries', sa.Column('recommendation', sa.Text(), nullable=True))
    op.add_column('trade_finance_queries', sa.Column('chain_of_thought', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_finance_queries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('destination_country', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('commodity_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('invoice_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trade_finance_queries_pkey')
    )
    # ### end Alembic commands ###
