"""Create users table

Revision ID: 2e10cdce8aa0
Revises: 4e9a18aa6a56
Create Date: 2025-02-24 12:53:08.186194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e10cdce8aa0'
down_revision: Union[str, None] = '4e9a18aa6a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_savings_plans_id', table_name='savings_plans')
    op.drop_table('savings_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('goal_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monthly_savings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('motivational_tips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='savings_plans_pkey')
    )
    op.create_index('ix_savings_plans_id', 'savings_plans', ['id'], unique=False)
    # ### end Alembic commands ###
