"""Add user_id to InvestmentPortfolio

Revision ID: 443a85cd8458
Revises: b913e208c0b7
Create Date: 2025-02-25 23:07:07.824612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443a85cd8458'
down_revision: Union[str, None] = 'b913e208c0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'income', 'users', ['user_id'], ['id'])
    op.add_column('investment_portfolios', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'investment_portfolios', 'users', ['user_id'], ['id'])
    op.add_column('news', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('news', sa.Column('analysis', sa.Text(), nullable=False))
    op.add_column('news', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('news', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'news', 'users', ['user_id'], ['id'])
    op.drop_column('news', 'content')
    op.drop_column('news', 'title')
    op.drop_column('news', 'source')
    op.add_column('savings_plans', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_plans', 'created_at')
    op.add_column('news', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('news', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('news', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'created_at')
    op.drop_column('news', 'user_id')
    op.drop_column('news', 'analysis')
    op.drop_column('news', 'topic')
    op.drop_constraint(None, 'investment_portfolios', type_='foreignkey')
    op.drop_column('investment_portfolios', 'user_id')
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'user_id')
    # ### end Alembic commands ###
