"""Create investment portfolio and assets tables

Revision ID: 4e9a18aa6a56
Revises: afc4eb9bf1ca
Create Date: 2025-02-24 00:38:24.473057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9a18aa6a56'
down_revision: Union[str, None] = 'afc4eb9bf1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_portfolios_id'), 'investment_portfolios', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('stock', 'real_estate', 'gold', 'bank_deposit', name='assettype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['investment_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.drop_index('ix_savings_plans_id', table_name='savings_plans')
    op.drop_table('savings_plans')
    op.drop_index('ix_investments_id', table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='investments_pkey')
    )
    op.create_index('ix_investments_id', 'investments', ['id'], unique=False)
    op.create_table('savings_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('goal_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monthly_savings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('motivational_tips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='savings_plans_pkey')
    )
    op.create_index('ix_savings_plans_id', 'savings_plans', ['id'], unique=False)
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_investment_portfolios_id'), table_name='investment_portfolios')
    op.drop_table('investment_portfolios')
    # ### end Alembic commands ###
