"""Refactor spending to income

Revision ID: 563f1fd6bd8c
Revises: b2d64ec1cd28
Create Date: 2025-02-23 12:07:22.416784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '563f1fd6bd8c'
down_revision: Union[str, None] = 'b2d64ec1cd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ Drop foreign key constraint from `expenses`
    op.drop_constraint('expenses_spending_id_fkey', 'expenses', type_='foreignkey')

    # 2️⃣ Rename `spending_id` column to `income_id` in `expenses`
    op.alter_column('expenses', 'spending_id', new_column_name='income_id')

    # 3️⃣ Drop the `spending` table safely
    op.drop_table('spending')

    # 4️⃣ Add new foreign key constraint linking `expenses.income_id` to `income.id`
    op.create_foreign_key(
        'expenses_income_id_fkey', 'expenses', 'income', ['income_id'], ['id']
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('spending_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_spending_id_fkey', 'expenses', 'spending', ['spending_id'], ['id'], ondelete='CASCADE')
    op.drop_column('expenses', 'income_id')
    op.create_table('spending',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monthly_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='spending_pkey')
    )
    op.create_index('ix_spending_id', 'spending', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
