"""Create research_queries table

Revision ID: 896f4cd2f9fc
Revises: a20a3800ebaf
Create Date: 2025-02-26 17:51:47.680620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896f4cd2f9fc'
down_revision: Union[str, None] = 'a20a3800ebaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('news', sa.Column('analysis', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'analysis')
    op.drop_column('news', 'topic')
    # ### end Alembic commands ###
