"""Add goal_name and desired_return_rate to savings_plans

Revision ID: a20a3800ebaf
Revises: 781f45c1cc46
Create Date: 2025-02-26 15:45:57.055018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20a3800ebaf'
down_revision: Union[str, None] = '781f45c1cc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add columns as nullable
    op.add_column('savings_plans', sa.Column('goal_name', sa.String(255), nullable=True))
    op.add_column('savings_plans', sa.Column('desired_return_rate', sa.Float(), nullable=True))

    # Step 2: Set default values for existing records
    op.execute("UPDATE savings_plans SET goal_name = 'Goal' WHERE goal_name IS NULL")
    op.execute("UPDATE savings_plans SET desired_return_rate = 0.0 WHERE desired_return_rate IS NULL")

    # Step 3: Make the columns NOT NULL now that we ensured default values
    op.alter_column('savings_plans', 'goal_name', existing_type=sa.String(255), nullable=False)
    op.alter_column('savings_plans', 'desired_return_rate', existing_type=sa.Float(), nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_plans', 'desired_return_rate')
    op.drop_column('savings_plans', 'goal_name')
    op.drop_column('news', 'analysis')
    op.drop_column('news', 'topic')
    # ### end Alembic commands ###
