"""Fix spending model

Revision ID: fc1289463c5f
Revises: fe5083fe6277
Create Date: 2025-02-23 12:38:01.812657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc1289463c5f'
down_revision: Union[str, None] = 'fe5083fe6277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_savings_plans_id', table_name='savings_plans')
    op.drop_table('savings_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='savings_plans_pkey')
    )
    op.create_index('ix_savings_plans_id', 'savings_plans', ['id'], unique=False)
    # ### end Alembic commands ###
